# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'common_options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 464)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.options_layout = QtWidgets.QGridLayout()
        self.options_layout.setHorizontalSpacing(4)
        self.options_layout.setVerticalSpacing(7)
        self.options_layout.setObjectName("options_layout")
        self.lbl_topic = QtWidgets.QLabel(Dialog)
        self.lbl_topic.setObjectName("lbl_topic")
        self.options_layout.addWidget(self.lbl_topic, 2, 0, 1, 1)
        self.edit_year = QtWidgets.QLineEdit(Dialog)
        self.edit_year.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edit_year.setObjectName("edit_year")
        self.options_layout.addWidget(self.edit_year, 4, 1, 1, 1)
        self.lbl_discipline = QtWidgets.QLabel(Dialog)
        self.lbl_discipline.setObjectName("lbl_discipline")
        self.options_layout.addWidget(self.lbl_discipline, 6, 0, 1, 1)
        self.lbl_year = QtWidgets.QLabel(Dialog)
        self.lbl_year.setObjectName("lbl_year")
        self.options_layout.addWidget(self.lbl_year, 4, 0, 1, 1)
        self.lbl_qual = QtWidgets.QLabel(Dialog)
        self.lbl_qual.setObjectName("lbl_qual")
        self.options_layout.addWidget(self.lbl_qual, 3, 3, 1, 1)
        self.edit_fac = QtWidgets.QLineEdit(Dialog)
        self.edit_fac.setMaximumSize(QtCore.QSize(500, 16777215))
        self.edit_fac.setObjectName("edit_fac")
        self.options_layout.addWidget(self.edit_fac, 7, 1, 1, 1)
        self.lbl_group_code = QtWidgets.QLabel(Dialog)
        self.lbl_group_code.setWordWrap(True)
        self.lbl_group_code.setObjectName("lbl_group_code")
        self.options_layout.addWidget(self.lbl_group_code, 5, 3, 1, 1)
        self.edit_group_code = QtWidgets.QLineEdit(Dialog)
        self.edit_group_code.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edit_group_code.setObjectName("edit_group_code")
        self.options_layout.addWidget(self.edit_group_code, 5, 4, 1, 1)
        self.edit_discipline = QtWidgets.QLineEdit(Dialog)
        self.edit_discipline.setObjectName("edit_discipline")
        self.options_layout.addWidget(self.edit_discipline, 6, 1, 1, 1)
        self.lbl_teacher_duty = QtWidgets.QLabel(Dialog)
        self.lbl_teacher_duty.setObjectName("lbl_teacher_duty")
        self.options_layout.addWidget(self.lbl_teacher_duty, 0, 3, 1, 1)
        self.edit_teacher = QtWidgets.QLineEdit(Dialog)
        self.edit_teacher.setObjectName("edit_teacher")
        self.options_layout.addWidget(self.edit_teacher, 0, 1, 1, 1)
        self.lbl_group_name = QtWidgets.QLabel(Dialog)
        self.lbl_group_name.setObjectName("lbl_group_name")
        self.options_layout.addWidget(self.lbl_group_name, 5, 0, 1, 1)
        self.edit_chair = QtWidgets.QLineEdit(Dialog)
        self.edit_chair.setMaximumSize(QtCore.QSize(500, 16777215))
        self.edit_chair.setObjectName("edit_chair")
        self.options_layout.addWidget(self.edit_chair, 8, 1, 1, 4)
        self.lbl_edit_short = QtWidgets.QLabel(Dialog)
        self.lbl_edit_short.setWordWrap(True)
        self.lbl_edit_short.setObjectName("lbl_edit_short")
        self.options_layout.addWidget(self.lbl_edit_short, 9, 0, 1, 1)
        self.edit_group_name = QtWidgets.QLineEdit(Dialog)
        self.edit_group_name.setMaximumSize(QtCore.QSize(150, 16777215))
        self.edit_group_name.setObjectName("edit_group_name")
        self.options_layout.addWidget(self.edit_group_name, 5, 1, 1, 1)
        self.edit_chair_short = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_chair_short.sizePolicy().hasHeightForWidth())
        self.edit_chair_short.setSizePolicy(sizePolicy)
        self.edit_chair_short.setMaximumSize(QtCore.QSize(150, 16777215))
        self.edit_chair_short.setObjectName("edit_chair_short")
        self.options_layout.addWidget(self.edit_chair_short, 9, 1, 1, 1)
        self.lbl_fac = QtWidgets.QLabel(Dialog)
        self.lbl_fac.setObjectName("lbl_fac")
        self.options_layout.addWidget(self.lbl_fac, 7, 0, 1, 1)
        self.edit_topic = QtWidgets.QLineEdit(Dialog)
        self.edit_topic.setEnabled(True)
        self.edit_topic.setObjectName("edit_topic")
        self.options_layout.addWidget(self.edit_topic, 2, 1, 1, 3)
        self.edit_qual = QtWidgets.QLineEdit(Dialog)
        self.edit_qual.setObjectName("edit_qual")
        self.options_layout.addWidget(self.edit_qual, 3, 4, 1, 1)
        self.lbl_chair = QtWidgets.QLabel(Dialog)
        self.lbl_chair.setObjectName("lbl_chair")
        self.options_layout.addWidget(self.lbl_chair, 8, 0, 1, 1)
        self.lbl_teacher = QtWidgets.QLabel(Dialog)
        self.lbl_teacher.setObjectName("lbl_teacher")
        self.options_layout.addWidget(self.lbl_teacher, 0, 0, 1, 1)
        self.box_work_type = QtWidgets.QComboBox(Dialog)
        self.box_work_type.setMinimumSize(QtCore.QSize(200, 0))
        self.box_work_type.setObjectName("box_work_type")
        self.options_layout.addWidget(self.box_work_type, 3, 1, 1, 1)
        self.edit_teacher_duty = QtWidgets.QLineEdit(Dialog)
        self.edit_teacher_duty.setObjectName("edit_teacher_duty")
        self.options_layout.addWidget(self.edit_teacher_duty, 0, 4, 1, 1)
        self.lbl_work_type = QtWidgets.QLabel(Dialog)
        self.lbl_work_type.setObjectName("lbl_work_type")
        self.options_layout.addWidget(self.lbl_work_type, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.options_layout, 0, 0, 1, 1)
        self.btn_apply = QtWidgets.QDialogButtonBox(Dialog)
        self.btn_apply.setGeometry(QtCore.QRect(377, 423, 151, 31))
        self.btn_apply.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.btn_apply.setOrientation(QtCore.Qt.Horizontal)
        self.btn_apply.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel)
        self.btn_apply.setCenterButtons(True)
        self.btn_apply.setObjectName("btn_apply")

        self.retranslateUi(Dialog)
        self.btn_apply.accepted.connect(Dialog.accept)
        self.btn_apply.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.edit_teacher, self.edit_teacher_duty)
        Dialog.setTabOrder(self.edit_teacher_duty, self.edit_topic)
        Dialog.setTabOrder(self.edit_topic, self.box_work_type)
        Dialog.setTabOrder(self.box_work_type, self.edit_qual)
        Dialog.setTabOrder(self.edit_qual, self.edit_year)
        Dialog.setTabOrder(self.edit_year, self.edit_group_name)
        Dialog.setTabOrder(self.edit_group_name, self.edit_group_code)
        Dialog.setTabOrder(self.edit_group_code, self.edit_discipline)
        Dialog.setTabOrder(self.edit_discipline, self.edit_fac)
        Dialog.setTabOrder(self.edit_fac, self.edit_chair)
        Dialog.setTabOrder(self.edit_chair, self.edit_chair_short)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Изменение общих параметров"))
        self.lbl_topic.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Тема работы*</span></p></body></html>"))
        self.lbl_discipline.setText(_translate("Dialog", "Дисциплина"))
        self.lbl_year.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Год сдачи*</span></p></body></html>"))
        self.lbl_qual.setText(_translate("Dialog", "Квалификация"))
        self.lbl_group_code.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Номер специальности*</span></p></body></html>"))
        self.lbl_teacher_duty.setText(_translate("Dialog", "Должность"))
        self.lbl_group_name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Группа*</span></p></body></html>"))
        self.lbl_edit_short.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Сокращенное название кафедры*</span></p></body></html>"))
        self.lbl_fac.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Институт*</span></p></body></html>"))
        self.lbl_chair.setText(_translate("Dialog", "<html><head/><body><p>Кафедра</p></body></html>"))
        self.lbl_teacher.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Руководитель*</span></p></body></html>"))
        self.lbl_work_type.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Категория работ*</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
