# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'common_options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 442)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.options_layout = QtWidgets.QGridLayout()
        self.options_layout.setObjectName("options_layout")
        self.lbl_chair = QtWidgets.QLabel(Dialog)
        self.lbl_chair.setObjectName("lbl_chair")
        self.options_layout.addWidget(self.lbl_chair, 9, 0, 1, 1)
        self.lbl_group_name = QtWidgets.QLabel(Dialog)
        self.lbl_group_name.setObjectName("lbl_group_name")
        self.options_layout.addWidget(self.lbl_group_name, 5, 0, 1, 1)
        self.lbl_fac = QtWidgets.QLabel(Dialog)
        self.lbl_fac.setObjectName("lbl_fac")
        self.options_layout.addWidget(self.lbl_fac, 8, 0, 1, 1)
        self.edit_group_code = QtWidgets.QLineEdit(Dialog)
        self.edit_group_code.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edit_group_code.setObjectName("edit_group_code")
        self.options_layout.addWidget(self.edit_group_code, 5, 4, 1, 1)
        self.edit_year = QtWidgets.QLineEdit(Dialog)
        self.edit_year.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edit_year.setObjectName("edit_year")
        self.options_layout.addWidget(self.edit_year, 4, 1, 1, 1)
        self.edit_teacher_duty = QtWidgets.QLineEdit(Dialog)
        self.edit_teacher_duty.setObjectName("edit_teacher_duty")
        self.options_layout.addWidget(self.edit_teacher_duty, 0, 4, 1, 1)
        self.lbl_teacher_duty = QtWidgets.QLabel(Dialog)
        self.lbl_teacher_duty.setObjectName("lbl_teacher_duty")
        self.options_layout.addWidget(self.lbl_teacher_duty, 0, 3, 1, 1)
        self.box_work_type = QtWidgets.QComboBox(Dialog)
        self.box_work_type.setMinimumSize(QtCore.QSize(200, 0))
        self.box_work_type.setObjectName("box_work_type")
        self.options_layout.addWidget(self.box_work_type, 3, 1, 1, 1)
        self.edit_teacher = QtWidgets.QLineEdit(Dialog)
        self.edit_teacher.setObjectName("edit_teacher")
        self.options_layout.addWidget(self.edit_teacher, 0, 1, 1, 1)
        self.lbl_year = QtWidgets.QLabel(Dialog)
        self.lbl_year.setObjectName("lbl_year")
        self.options_layout.addWidget(self.lbl_year, 4, 0, 1, 1)
        self.lbl_profile = QtWidgets.QLabel(Dialog)
        self.lbl_profile.setObjectName("lbl_profile")
        self.options_layout.addWidget(self.lbl_profile, 6, 3, 1, 1)
        self.lbl_topic = QtWidgets.QLabel(Dialog)
        self.lbl_topic.setObjectName("lbl_topic")
        self.options_layout.addWidget(self.lbl_topic, 2, 0, 1, 1)
        self.lbl_study = QtWidgets.QLabel(Dialog)
        self.lbl_study.setObjectName("lbl_study")
        self.options_layout.addWidget(self.lbl_study, 6, 0, 1, 1)
        self.lbl_edit_short = QtWidgets.QLabel(Dialog)
        self.lbl_edit_short.setObjectName("lbl_edit_short")
        self.options_layout.addWidget(self.lbl_edit_short, 10, 0, 1, 1)
        self.edit_chair_short = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_chair_short.sizePolicy().hasHeightForWidth())
        self.edit_chair_short.setSizePolicy(sizePolicy)
        self.edit_chair_short.setMaximumSize(QtCore.QSize(150, 16777215))
        self.edit_chair_short.setObjectName("edit_chair_short")
        self.options_layout.addWidget(self.edit_chair_short, 10, 1, 1, 1)
        self.lbl_work_type = QtWidgets.QLabel(Dialog)
        self.lbl_work_type.setObjectName("lbl_work_type")
        self.options_layout.addWidget(self.lbl_work_type, 3, 0, 1, 1)
        self.lbl_teacher = QtWidgets.QLabel(Dialog)
        self.lbl_teacher.setObjectName("lbl_teacher")
        self.options_layout.addWidget(self.lbl_teacher, 0, 0, 1, 1)
        self.edit_fac = QtWidgets.QLineEdit(Dialog)
        self.edit_fac.setMaximumSize(QtCore.QSize(500, 16777215))
        self.edit_fac.setObjectName("edit_fac")
        self.options_layout.addWidget(self.edit_fac, 8, 1, 1, 1)
        self.edit_group_name = QtWidgets.QLineEdit(Dialog)
        self.edit_group_name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_group_name.setObjectName("edit_group_name")
        self.options_layout.addWidget(self.edit_group_name, 5, 1, 1, 1)
        self.edit_profile = QtWidgets.QLineEdit(Dialog)
        self.edit_profile.setObjectName("edit_profile")
        self.options_layout.addWidget(self.edit_profile, 6, 4, 1, 1)
        self.edit_study = QtWidgets.QLineEdit(Dialog)
        self.edit_study.setObjectName("edit_study")
        self.options_layout.addWidget(self.edit_study, 6, 1, 1, 1)
        self.lbl_group_code = QtWidgets.QLabel(Dialog)
        self.lbl_group_code.setObjectName("lbl_group_code")
        self.options_layout.addWidget(self.lbl_group_code, 5, 3, 1, 1)
        self.lbl_discipline = QtWidgets.QLabel(Dialog)
        self.lbl_discipline.setObjectName("lbl_discipline")
        self.options_layout.addWidget(self.lbl_discipline, 7, 0, 1, 1)
        self.edit_discipline = QtWidgets.QLineEdit(Dialog)
        self.edit_discipline.setObjectName("edit_discipline")
        self.options_layout.addWidget(self.edit_discipline, 7, 1, 1, 1)
        self.edit_discipline_code = QtWidgets.QLineEdit(Dialog)
        self.edit_discipline_code.setObjectName("edit_discipline_code")
        self.options_layout.addWidget(self.edit_discipline_code, 7, 4, 1, 1)
        self.lbl_discipline_code = QtWidgets.QLabel(Dialog)
        self.lbl_discipline_code.setObjectName("lbl_discipline_code")
        self.options_layout.addWidget(self.lbl_discipline_code, 7, 3, 1, 1)
        self.lbl_qual = QtWidgets.QLabel(Dialog)
        self.lbl_qual.setObjectName("lbl_qual")
        self.options_layout.addWidget(self.lbl_qual, 3, 3, 1, 1)
        self.edit_topic = QtWidgets.QLineEdit(Dialog)
        self.edit_topic.setEnabled(True)
        self.edit_topic.setObjectName("edit_topic")
        self.options_layout.addWidget(self.edit_topic, 2, 1, 1, 3)
        self.edit_qual = QtWidgets.QLineEdit(Dialog)
        self.edit_qual.setObjectName("edit_qual")
        self.options_layout.addWidget(self.edit_qual, 3, 4, 1, 1)
        self.edit_chair = QtWidgets.QLineEdit(Dialog)
        self.edit_chair.setMaximumSize(QtCore.QSize(500, 16777215))
        self.edit_chair.setObjectName("edit_chair")
        self.options_layout.addWidget(self.edit_chair, 9, 1, 1, 4)
        self.gridLayout.addLayout(self.options_layout, 0, 0, 1, 1)
        self.btn_apply = QtWidgets.QDialogButtonBox(Dialog)
        self.btn_apply.setGeometry(QtCore.QRect(187, 403, 301, 31))
        self.btn_apply.setOrientation(QtCore.Qt.Horizontal)
        self.btn_apply.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_apply.setObjectName("btn_apply")

        self.retranslateUi(Dialog)
        self.btn_apply.accepted.connect(Dialog.accept)
        self.btn_apply.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Изменение общих параметров"))
        self.lbl_chair.setText(_translate("Dialog", "<html><head/><body><p>Кафедра</p></body></html>"))
        self.lbl_group_name.setText(_translate("Dialog", "Группа"))
        self.lbl_fac.setText(_translate("Dialog", "<html><head/><body><p>Фак/инст.</p></body></html>"))
        self.lbl_teacher_duty.setText(_translate("Dialog", "Должность"))
        self.lbl_year.setText(_translate("Dialog", "Год"))
        self.lbl_profile.setText(_translate("Dialog", "Профиль"))
        self.lbl_topic.setText(_translate("Dialog", "Тема работы"))
        self.lbl_study.setText(_translate("Dialog", "Направление"))
        self.lbl_edit_short.setText(_translate("Dialog", "Сокращ. Каф."))
        self.lbl_work_type.setText(_translate("Dialog", "Вид"))
        self.lbl_teacher.setText(_translate("Dialog", "Руководитель"))
        self.lbl_group_code.setText(_translate("Dialog", "Номер\n"
"специальности"))
        self.lbl_discipline.setText(_translate("Dialog", "Дисциплина"))
        self.lbl_discipline_code.setText(_translate("Dialog", "Код дисциплины"))
        self.lbl_qual.setText(_translate("Dialog", "Квалификация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

